# Generated by Django 4.1.1 on 2022-10-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perikanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jenis_Ikan', models.CharField(max_length=15)),
                ('Jenis_Usaha', models.CharField(max_length=30)),
                ('Tahun', models.IntegerField(null=True)),
                ('Volume_Produksi', models.CharField(max_length=30)),
                ('Nilai_Produksi', models.CharField(max_length=30)),
                ('Picture', models.ImageField(blank=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Tempat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsii', models.CharField(max_length=20)),
            ],
        ),
    ]
