# Generated by Django 4.1.1 on 2022-10-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_app', '0002_perikanan_provinsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='perikanan',
            name='Detail',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
