# Generated by Django 4.1.1 on 2022-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_app', '0003_perikanan_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perikanan',
            name='Picture',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
