# Generated by Django 4.1.1 on 2022-10-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_app', '0004_alter_perikanan_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perikanan',
            old_name='Picture',
            new_name='img',
        ),
    ]
