# Generated by Django 4.1.1 on 2022-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_app', '0005_rename_picture_perikanan_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perikanan',
            name='Detail',
            field=models.URLField(max_length=100),
        ),
    ]
